import React, { Component } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { styled } from '@mui/material/styles';
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Grid';

const Item = styled(Paper)(({ theme }) => ({
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: 'center',
  color: theme.palette.text.secondary,
  backgroundColor:"green"
}));

class Home extends Component {

   constructor (props) {
     super(props)
     this.state ={
       data :["Bala","Senthil","Kumar","Raja","Mani","Vadivel","Shiva", "Murugan"]
     }
   }
   


  render() {
    console.log("************bala***********************************")
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <marquee>Sample Next JS Project</marquee>          
      <Box sx={{ flexGrow: 1 }}>
      <Grid container spacing={2}>
        {this.state.data.map((item) =>
         <Grid item xs={6}>
          <Item >{item}</Item>
         </Grid>
        )}
       
       
      </Grid>
    </Box>
       
        </main>
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              Bala
            </span>
          </a>
        </footer>
      </div>
    );
  }
}
export default Home;